# Generated by Django 4.1.3 on 2022-12-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
